[package]
name = "wsfs-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
fuser = "0.14.0"
futures-util = "0.3.30"
lazy_static = "1.5.0"
pretty_env_logger = "0.5.0"
tokio = { version = "1.40.0", features = ["full"] }
warp = { version = "0.3.7", features = ["tls"] }
